# Generated by Django 3.2 on 2022-08-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20220823_0206'),
        ('test_river', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyworkflow',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='river.workflow'),
        ),
    ]
