# Generated by Django 3.2 on 2022-08-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_river', '0002_dummyworkflow_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyworkflow',
            name='workflow',
        ),
    ]
